-- Run this once in Supabase Dashboard → SQL Editor for the shared CampusConnect database.
-- Students use the publishable/anon key plus Supabase Auth. The Creator app uses
-- SUPABASE_SERVICE_ROLE_KEY only on its server and is protected by a creator password.

create table if not exists public.campus_groups (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    department text not null,
    semester smallint check (semester is null or semester between 1 and 8),
    description text not null default '',
    created_by uuid references auth.users(id) on delete set null,
    created_by_name text not null default 'CampusConnect',
    is_default boolean not null default false,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create unique index if not exists campus_groups_default_unique
    on public.campus_groups (department, semester) where is_default = true;

create table if not exists public.group_members (
    group_id uuid not null references public.campus_groups(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    display_name text not null,
    joined_at timestamptz not null default now(),
    primary key (group_id, user_id)
);

create table if not exists public.group_messages (
    id bigint generated by default as identity primary key,
    group_id uuid not null references public.campus_groups(id) on delete cascade,
    sender_id uuid not null references auth.users(id) on delete cascade,
    display_name text not null,
    message text not null check (char_length(message) between 1 and 2000),
    created_at timestamptz not null default now()
);
alter table public.group_messages add column if not exists image_path text;
alter table public.group_messages alter column message set default '';
alter table public.group_messages drop constraint if exists group_messages_message_check;
alter table public.group_messages add constraint group_messages_message_check
    check (char_length(message) <= 2000 and (char_length(message) > 0 or image_path is not null));
create index if not exists group_messages_group_created_idx
    on public.group_messages (group_id, created_at desc);

-- One student alert choice per local campus day. Green choices accrue in-app credits only.
create table if not exists public.student_daily_choices (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    choice_date date not null default (now() at time zone 'Asia/Kolkata')::date,
    choice text not null check (choice in ('red', 'yellow', 'green')),
    created_at timestamptz not null default now(),
    unique (user_id, choice_date)
);

-- Private student-to-creator inbox. Students can only read their own conversation.
create table if not exists public.student_creator_messages (
    id bigint generated by default as identity primary key,
    student_id uuid not null references auth.users(id) on delete cascade,
    student_name text not null,
    sender_role text not null check (sender_role in ('student', 'creator')),
    message text not null check (char_length(message) between 1 and 2000),
    created_at timestamptz not null default now()
);
create index if not exists student_creator_messages_student_created_idx
    on public.student_creator_messages (student_id, created_at);

create table if not exists public.campus_posts (
    id uuid primary key default gen_random_uuid(),
    kind text not null check (kind in ('Notice', 'Activity')),
    title text not null,
    body text not null,
    event_date date not null,
    audience text not null default 'All departments',
    created_by_name text not null,
    status text not null default 'draft' check (status in ('draft', 'published')),
    is_important boolean not null default false,
    is_special boolean not null default false,
    poster_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.campus_posts add column if not exists poster_url text;

create table if not exists public.student_feedback (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    display_name text not null,
    topic text not null,
    message text not null check (char_length(message) between 1 and 2000),
    created_at timestamptz not null default now()
);

-- Creator-managed public campus links. Values are links only, never API keys.
create table if not exists public.campus_settings (
    key text primary key check (key in ('whatsapp_community_url', 'whatsapp_channel_url', 'google_calendar_embed_url')),
    value text not null default '',
    updated_at timestamptz not null default now()
);

-- Public poster artwork is intended for campus notices and activities.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('campus-posters', 'campus-posters', true, 8388608, array['image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- Group photos are private. Students use short-lived signed URLs to display them.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('group-chat-photos', 'group-chat-photos', false, 5242880, array['image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- Aggregate page views only; no student identity or message content is stored.
create table if not exists public.campus_app_views (
    id bigint generated by default as identity primary key,
    page_name text not null,
    created_at timestamptz not null default now()
);

-- Seed a department study group for every semester (9 departments × 8 semesters).
insert into public.campus_groups (name, department, semester, description, created_by_name, is_default)
select
    department || ' · Semester ' || semester,
    department,
    semester,
    'Study and class discussion for ' || department || ', semester ' || semester || '.',
    'CampusConnect',
    true
from unnest(array['CSE','IT','ECE','EEE','Mechanical','Civil','Chemical','Biotechnology','Other']) as departments(department)
cross join generate_series(1, 8) as semesters(semester)
on conflict (department, semester) where is_default = true do nothing;

-- Lock down all exposed tables; the creator app's service-role key is server-only.
grant usage on schema public to authenticated;
alter table public.campus_groups enable row level security;
alter table public.group_members enable row level security;
alter table public.group_messages enable row level security;
alter table public.campus_posts enable row level security;
alter table public.student_feedback enable row level security;
alter table public.campus_settings enable row level security;
alter table public.campus_app_views enable row level security;
alter table public.student_daily_choices enable row level security;
alter table public.student_creator_messages enable row level security;

revoke all on public.campus_groups, public.group_members, public.group_messages,
    public.campus_posts, public.student_feedback, public.campus_settings, public.campus_app_views,
    public.student_daily_choices, public.student_creator_messages from anon;

grant select, insert on public.campus_groups to authenticated;
grant select, insert, delete on public.group_members to authenticated;
grant select, insert, delete on public.group_messages to authenticated;
grant select on public.campus_posts to authenticated;
grant insert on public.student_feedback to authenticated;
grant select on public.campus_settings to authenticated;
grant insert on public.campus_app_views to authenticated;
grant select, insert on public.student_daily_choices to authenticated;
grant select, insert on public.student_creator_messages to authenticated;

drop policy if exists "Students see active groups" on public.campus_groups;
create policy "Students see active groups"
    on public.campus_groups for select to authenticated using (is_active = true);

drop policy if exists "Students create groups as themselves" on public.campus_groups;
create policy "Students create groups as themselves"
    on public.campus_groups for insert to authenticated
    with check (created_by = (select auth.uid()));

drop policy if exists "Students see their own memberships" on public.group_members;
create policy "Students see their own memberships"
    on public.group_members for select to authenticated
    using (user_id = (select auth.uid()));

drop policy if exists "Students join as themselves" on public.group_members;
create policy "Students join as themselves"
    on public.group_members for insert to authenticated
    with check (
        user_id = (select auth.uid())
        and exists (select 1 from public.campus_groups g where g.id = group_id and g.is_active = true)
    );

drop policy if exists "Students leave their own memberships" on public.group_members;
create policy "Students leave their own memberships"
    on public.group_members for delete to authenticated
    using (user_id = (select auth.uid()));

drop policy if exists "Group members read messages" on public.group_messages;
create policy "Group members read messages"
    on public.group_messages for select to authenticated
    using (
        exists (
            select 1 from public.group_members m
            where m.group_id = group_messages.group_id and m.user_id = (select auth.uid())
        )
    );

drop policy if exists "Group members send their own messages" on public.group_messages;
create policy "Group members send their own messages"
    on public.group_messages for insert to authenticated
    with check (
        sender_id = (select auth.uid())
        and (image_path is null or image_path like group_messages.group_id::text || '/' || (select auth.uid())::text || '/%')
        and exists (
            select 1 from public.group_members m
            where m.group_id = group_messages.group_id and m.user_id = (select auth.uid())
        )
    );

drop policy if exists "Students delete their own group messages" on public.group_messages;
create policy "Students delete their own group messages"
    on public.group_messages for delete to authenticated
    using (
        sender_id = (select auth.uid())
        and exists (
            select 1 from public.group_members m
            where m.group_id = group_messages.group_id and m.user_id = (select auth.uid())
        )
    );

drop policy if exists "Students read published campus updates" on public.campus_posts;
create policy "Students read published campus updates"
    on public.campus_posts for select to authenticated
    using (status = 'published');

drop policy if exists "Students send their own feedback" on public.student_feedback;
create policy "Students send their own feedback"
    on public.student_feedback for insert to authenticated
    with check (user_id = (select auth.uid()));

drop policy if exists "Students read public campus links" on public.campus_settings;
create policy "Students read public campus links"
    on public.campus_settings for select to authenticated using (true);

drop policy if exists "Students record page views" on public.campus_app_views;
create policy "Students record page views"
    on public.campus_app_views for insert to authenticated
    with check (page_name in ('Home', 'Study Groups', 'Group Chat', 'Chat with Creator', 'Campus Calendar', 'Campus Activities', 'Notices', 'AI Study Buddy', 'AI Search', 'WhatsApp', 'Feedback'));

drop policy if exists "Students view their own daily choices" on public.student_daily_choices;
create policy "Students view their own daily choices"
    on public.student_daily_choices for select to authenticated
    using (user_id = (select auth.uid()));

drop policy if exists "Students choose once each day" on public.student_daily_choices;
create policy "Students choose once each day"
    on public.student_daily_choices for insert to authenticated
    with check (
        user_id = (select auth.uid())
        and choice_date = (now() at time zone 'Asia/Kolkata')::date
    );

drop policy if exists "Students read their own creator chat" on public.student_creator_messages;
create policy "Students read their own creator chat"
    on public.student_creator_messages for select to authenticated
    using (student_id = (select auth.uid()));

drop policy if exists "Students send creator chat messages as themselves" on public.student_creator_messages;
create policy "Students send creator chat messages as themselves"
    on public.student_creator_messages for insert to authenticated
    with check (student_id = (select auth.uid()) and sender_role = 'student');

drop policy if exists "Group members upload their own group photos" on storage.objects;
create policy "Group members upload their own group photos"
    on storage.objects for insert to authenticated
    with check (
        bucket_id = 'group-chat-photos'
        and (storage.foldername(name))[2] = (select auth.uid())::text
        and exists (
            select 1 from public.group_members m
            where m.group_id::text = (storage.foldername(name))[1]
              and m.user_id = (select auth.uid())
        )
    );

drop policy if exists "Group members read group photos" on storage.objects;
create policy "Group members read group photos"
    on storage.objects for select to authenticated
    using (
        bucket_id = 'group-chat-photos'
        and exists (
            select 1 from public.group_members m
            where m.group_id::text = (storage.foldername(name))[1]
              and m.user_id = (select auth.uid())
        )
    );

drop policy if exists "Students delete their own group photos" on storage.objects;
create policy "Students delete their own group photos"
    on storage.objects for delete to authenticated
    using (
        bucket_id = 'group-chat-photos'
        and (storage.foldername(name))[2] = (select auth.uid())::text
        and exists (
            select 1 from public.group_members m
            where m.group_id::text = (storage.foldername(name))[1]
              and m.user_id = (select auth.uid())
        )
    );
