-- Run this once in Supabase Dashboard → SQL Editor for the shared CampusConnect database.
-- Students use the publishable/anon key plus Supabase Auth. The Creator app uses
-- SUPABASE_SERVICE_ROLE_KEY only on its server and is protected by a creator password.

create table if not exists public.campus_groups (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    department text not null,
    semester smallint check (semester is null or semester between 1 and 8),
    description text not null default '',
    created_by uuid references auth.users(id) on delete set null,
    created_by_name text not null default 'CampusConnect',
    is_default boolean not null default false,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create unique index if not exists campus_groups_default_unique
    on public.campus_groups (department, semester) where is_default = true;

create table if not exists public.group_members (
    group_id uuid not null references public.campus_groups(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    display_name text not null,
    joined_at timestamptz not null default now(),
    primary key (group_id, user_id)
);

create table if not exists public.group_messages (
    id bigint generated by default as identity primary key,
    group_id uuid not null references public.campus_groups(id) on delete cascade,
    sender_id uuid not null references auth.users(id) on delete cascade,
    display_name text not null,
    message text not null check (char_length(message) between 1 and 2000),
    created_at timestamptz not null default now()
);
create index if not exists group_messages_group_created_idx
    on public.group_messages (group_id, created_at desc);

create table if not exists public.campus_posts (
    id uuid primary key default gen_random_uuid(),
    kind text not null check (kind in ('Notice', 'Activity')),
    title text not null,
    body text not null,
    event_date date not null,
    audience text not null default 'All departments',
    created_by_name text not null,
    status text not null default 'draft' check (status in ('draft', 'published')),
    is_important boolean not null default false,
    is_special boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.student_feedback (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    display_name text not null,
    topic text not null,
    message text not null check (char_length(message) between 1 and 2000),
    created_at timestamptz not null default now()
);

-- Creator-managed public campus links. Values are links only, never API keys.
create table if not exists public.campus_settings (
    key text primary key check (key in ('whatsapp_community_url', 'whatsapp_channel_url', 'google_calendar_embed_url')),
    value text not null default '',
    updated_at timestamptz not null default now()
);

-- Seed a department study group for every semester (9 departments × 8 semesters).
insert into public.campus_groups (name, department, semester, description, created_by_name, is_default)
select
    department || ' · Semester ' || semester,
    department,
    semester,
    'Study and class discussion for ' || department || ', semester ' || semester || '.',
    'CampusConnect',
    true
from unnest(array['CSE','IT','ECE','EEE','Mechanical','Civil','Chemical','Biotechnology','Other']) as departments(department)
cross join generate_series(1, 8) as semesters(semester)
on conflict (department, semester) where is_default = true do nothing;

-- Lock down all exposed tables; the creator app's service-role key is server-only.
grant usage on schema public to authenticated;
alter table public.campus_groups enable row level security;
alter table public.group_members enable row level security;
alter table public.group_messages enable row level security;
alter table public.campus_posts enable row level security;
alter table public.student_feedback enable row level security;
alter table public.campus_settings enable row level security;

revoke all on public.campus_groups, public.group_members, public.group_messages,
    public.campus_posts, public.student_feedback, public.campus_settings from anon;

grant select, insert on public.campus_groups to authenticated;
grant select, insert, delete on public.group_members to authenticated;
grant select, insert on public.group_messages to authenticated;
grant select on public.campus_posts to authenticated;
grant insert on public.student_feedback to authenticated;
grant select on public.campus_settings to authenticated;

drop policy if exists "Students see active groups" on public.campus_groups;
create policy "Students see active groups"
    on public.campus_groups for select to authenticated using (is_active = true);

drop policy if exists "Students create groups as themselves" on public.campus_groups;
create policy "Students create groups as themselves"
    on public.campus_groups for insert to authenticated
    with check (created_by = (select auth.uid()));

drop policy if exists "Students see their own memberships" on public.group_members;
create policy "Students see their own memberships"
    on public.group_members for select to authenticated
    using (user_id = (select auth.uid()));

drop policy if exists "Students join as themselves" on public.group_members;
create policy "Students join as themselves"
    on public.group_members for insert to authenticated
    with check (
        user_id = (select auth.uid())
        and exists (select 1 from public.campus_groups g where g.id = group_id and g.is_active = true)
    );

drop policy if exists "Students leave their own memberships" on public.group_members;
create policy "Students leave their own memberships"
    on public.group_members for delete to authenticated
    using (user_id = (select auth.uid()));

drop policy if exists "Group members read messages" on public.group_messages;
create policy "Group members read messages"
    on public.group_messages for select to authenticated
    using (
        exists (
            select 1 from public.group_members m
            where m.group_id = group_messages.group_id and m.user_id = (select auth.uid())
        )
    );

drop policy if exists "Group members send their own messages" on public.group_messages;
create policy "Group members send their own messages"
    on public.group_messages for insert to authenticated
    with check (
        sender_id = (select auth.uid())
        and exists (
            select 1 from public.group_members m
            where m.group_id = group_messages.group_id and m.user_id = (select auth.uid())
        )
    );

drop policy if exists "Students read published campus updates" on public.campus_posts;
create policy "Students read published campus updates"
    on public.campus_posts for select to authenticated
    using (status = 'published');

drop policy if exists "Students send their own feedback" on public.student_feedback;
create policy "Students send their own feedback"
    on public.student_feedback for insert to authenticated
    with check (user_id = (select auth.uid()));

drop policy if exists "Students read public campus links" on public.campus_settings;
create policy "Students read public campus links"
    on public.campus_settings for select to authenticated using (true);
